# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-KR   
  title: 김동훈 포트폴리오
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
us:
  languageCode: us-US 
  title: KDH Portfolio
  weight: 2

  #contentDir: content/zh
  #title: Chinese website title...
  #params:
   # description: Site description in Chinese...
  #menu:
   # main:
    #  - name: 传
     #   url: '#about'
      #  weight: 1
